---
name: AO
filename: Awesome_oscillator_-_extended
class: ZeroLineCross
inputs:
# input ENUM_TIMEFRAMES TimeFrame         = PERIOD_CURRENT; // Time frame
  - - Int
    - - 0.0  # current
      # - 1.0  # M1
      - 5.0  # M5
      - 19.0 # D1
      # - 21.0 # MN1
      - 2.0    # 5m 10m 15m 30m 2h 4h 8h 1D
# input enMaTypes       MaMethod1         = ma_sma;    // Fast average method
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input int             MaPeriod1         = 5;         // Faste average period
  - - Int
    - - 5.0
      - 3.0
      - 15.0
      - 2.0
# input enPrices        MaPrice1          = pr_median; // Fast average price
  - - Int
    - - 4.0
      - 0.0
      - 21.0
      - 1.0
# input enMaTypes       MaMethod2         = ma_sma;    // Slow average method
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input int             MaPeriod2         = 34;        // Slow average period
  - - Int
    - - 34.0
      - 22.0
      - 44.0
      - 2.0
# input enPrices        MaPrice2          = pr_median; // Slow average price
  - - Int
    - - 4.0
      - 0.0
      - 21.0
      - 1.0
# input bool            AlertsOn          = false;     // Turn alerts on?
# input bool            AlertsOnCurrent   = true;      // Alert on current bar?
# input bool            AlertsMessage     = true;      // Display messageas on alerts?
# input bool            AlertsSound       = false;     // Play sound on alerts?
# input bool            AlertsEmail       = false;     // Send email on alerts?
# input bool            AlertsNotify      = false;     // Send push notification on alerts?
# input bool            Interpolate       = true;           // Interpolate in multi time frame mode?
buffers:
   # SetIndexBuffer(0,aofu  ,INDICATOR_DATA);
   # SetIndexBuffer(1,aofd  ,INDICATOR_DATA);
   # SetIndexBuffer(2,histo ,INDICATOR_DATA);
   # SetIndexBuffer(3,histoc,INDICATOR_COLOR_INDEX);
   # SetIndexBuffer(4,ao    ,INDICATOR_DATA);
   # SetIndexBuffer(5,aoc   ,INDICATOR_COLOR_INDEX);
   # SetIndexBuffer(6,count ,INDICATOR_CALCULATIONS);
  - 4
shift: 0

