---
name: Chaikin
filename: chaikin
class: ZeroLineCross
inputs:
  ## XXX is included: IND_CHAIKIN

# input int                  fast_ma_period=3;             // Schnelle Zeitraum
  - - Int
    - - 3.0
      - 1.0
      - 8.0
      - 1.0
# input int                  slow_ma_period=10;            // Langsame Zeitraum
  - - Int
    - - 10.0
      - 5.0
      - 18.0
      - 1.0
# input ENUM_MA_METHOD       ma_method=MODE_EMA;           // Art der Gl√§ttung
  - - Int
    - - 1.0
      - 0.0
      - 3.0
      - 1.0
# input ENUM_APPLIED_VOLUME  applied_volume=VOLUME_TICK;   // Volumentyp
# VOLUME_REAL
  - - Int
    - - 1.0
      - 0.0
      - 1.0
      - 1.0
buffers:
  - 0
shift: 0

