---
name: Ssl
filename: ssl
class: Semaphore
inputs:
# input uint   period=13;           // Moving averages period;
  - - Int
    - - 13.0
      - 5.0
      - 25.0
      - 1.0
# input bool   NRTR=true;           // NRTR
# input int    Shift=0;             // Horizontal shift of the indicator in bars
buffers:
  # buy signal
  - 2
  # sell signal
  - 3
shift: 0

