---
name: ma
class: Preset
inputs:
   # MA
  - - 18.0
    - 40.0
    - 2.0
   # Shift
  - - 0.0
   # MA_METHOD Method
  - - 0.0
    - 3.0
    - 1.0
   # Applied Price
  - - 0.0
    - 6.0
    - 1.0
shift: 0
