---
name: volatility_ratio
filename: Volatility_ratio
# without ex5
class: TwoLevelsCross
inputs:
# input int                inpPeriod = 25;          // Volatility period
  - - Int
    - - 25.0
      - 13.0
      - 38.0
      - 2.0
# input ENUM_APPLIED_PRICE inpPrice  = PRICE_CLOSE; // Price
# PRICE_CLOSE 0 Close price
# PRICE_OPEN 1 Open price
# PRICE_HIGH 2 The maximum price for the period
# PRICE_LOW 3 The minimum price for the period
# PRICE_MEDIAN 4 Median price, (high + low)/2
# PRICE_TYPICAL 5 Typical price, (high + low + close)/3
# PRICE_WEIGHTED 6 Weighted close price, (high + low + close + close)/4
  - - Int
    - - 0.0
      - 0.0
      - 6.0
      - 1.0
buffers:
  - 0
levels:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
shift: 0

