---
name: wae
class: Preset
inputs:
  # Fast_MA=20
  - - 15.0
    - 25.0
    - 2.0
  # Slow_MA=40
  - - 30.0
    - 50.0
    - 2.0
  # BBPeriod=20
  - - 15.0
    - 25.0
    - 2.0
  # BBDeviation=2
  - - 1.0
    - 4.0
    - 1.0
  # Sensetive=150
  - - 50.0
    - 250.0
    - 50.0
  # DeadZonePip=400
  - - 400.0
  # ExplosionPower=15
  - - 15.0
  # TrendPower=150
  - - 50.0
    - 250.0
    - 50.0
  # AlertWindow=false
  # AlertCount=2
  - - 2.0
  # AlertLong=false
  # AlertShort=false
  # AlertExitLong=false
  # AlertExitShort=false
shift: 0
